### PR TITLE
tests folder

### PR DESCRIPTION
**Pull request by yossi-r**
tests folder under modules

### CODE REVIEW

**Comment by jmcalalang** [comment]
@yossi-r i wasnt on the call to talk about this, you want me to review? or @vinnie357

**Comment by vinnie357** [comment]
Can we maybe have an empty module_template folder at the base of modules like I did for solutions rather than pointing to a specific aws one?

**Review by vinnie357 — COMMENTED** [review]
Can we maybe have an empty module_template folder at the base of modules like I did for solutions rather than pointing to a specific aws one?

**Comment by jmcalalang** [comment]
I do like the idea of it generic, I could do the same for docs, then it's universal.

**Comment by yossi-r** [comment]
not relevant anymore

**Pull request closed without merging**
