### PR TITLE
fix gcp-nginx-plus example

### LINKED ISSUE #81: update nginx-plus-gcp
nginx plus gcp example not working with new network module.

### PR DESCRIPTION
**Pull request by vinnie357**
modify gcp min outputs
update nginx-plus variables to match new network module
update nginx-plus variables to match new naming standards
update terraform to 14.5 to support network module
closes #81

### CODE REVIEW

**Review by memes — APPROVED** [review]
LGTM

**Review by jmcalalang — APPROVED** [review]
google updates looks like object paths changed, and devcontainer update to new version of 14.5

**Comment by jmcalalang** [comment]
this get us closer to having a GCP NGINX solution?

**Comment by vinnie357** [comment]
yes, actually. well bringing them back in :D

**Pull request merged**
