### PR TITLE
Issue4 aws max

### LINKED ISSUE #4: ## Network AWS max
- [x] terraform
- [x] documentation
- [ ] diagrams
- [x] examples

### PR DESCRIPTION
**Pull request by merps**
# Pull Request

## Description

This is the initial AWS Max example module that uses the vendor registry module as a base.  The following has been supplied:

- [x] terraform code
- [ ] network diagram
- [x] documentation

## Fixes

Fixes #4 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

Basic validation and init has been performed using the attach example

- [x] `terraform init`
- [x] `terraform validate`

**Test Configuration**:
```
Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/aws v3.27.0
+ provider registry.terraform.io/hashicorp/random v3.0.1
```

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by jmcalalang — COMMENTED** [review]
What's with the google storage bucket? Otherwise, this is all new, I'm good for it.

Are you owning this module now or is @yossi-r ? should we update codeowners too so nothing happens without your awareness

**Comment by merps** [comment]
@jmcalalang - thanks for the heads up on the storage bucket... I shall pull this PR..

**Comment by merps** [comment]
@jmcalalang  - forgive my stupidity mate - which commit is the google storage bucket in?

**Comment by jmcalalang** [comment]
modules/google/terraform/network/max/main.tf

Its in here very last file if you look at Files Changed

**Comment by merps** [comment]
it's actually the first @jmcalalang  - but hey...

**Pull request closed without merging**
